In [119]:
import pandas as pd
import numpy as np

rows = ['A', 'B', 'C', 'D']
columns = ['Monday', 'Tuesday', 'Wednesday', 'Thursday','Friday']
data_array = np.random.randn(4, 5)

print(data_array)

data_frame = pd.DataFrame(data_array, columns=columns, index=rows)
data_frame

[[ 0.42675879 -0.82284463  1.38892261  1.07561252 -0.08407631]
 [-0.4079019  -0.00596427  0.4904139   0.3258548   0.92486533]
 [ 0.12562958 -0.00656087  1.70729706 -1.66451301 -2.61273763]
 [-2.56553561 -0.61572048 -0.35400357  0.24449643 -0.54448894]]


Monday   Tuesday  Wednesday  Thursday    Friday
A  0.426759 -0.822845   1.388923  1.075613 -0.084076
B -0.407902 -0.005964   0.490414  0.325855  0.924865
C  0.125630 -0.006561   1.707297 -1.664513 -2.612738
D -2.565536 -0.615720  -0.354004  0.244496 -0.544489

**Simple dataframe operations**

#data_frame.dtypes #types of columns' fields

#data_frame.describe() - statics data

#data_frame.head(2)

#data_frame.index

#data_frame.columns

#data_frame.values

**Transpose and other imp**

#data_frame.T - Flips columns and indexes(Transpose)

#data_frame.sort_values(by=['Monday'], ascending=False) - what it does it goes to the collmn of monday and sort it values descending

#data_frame[1:3] # slice the rows from index 1 to index 2 (3 is not inlcuded, and first index is 0)

#data_frame[['Monday','Friday']] # slice the colums

#df2 = data_frame.copy() # creates a copy of thr data frame

#iloc - integer location

#loc - location


#data_frame.loc['C','Monday'] = 2 - loc['row','Column'] - to replace a value

#data_frame['Monday'].mean() - creates mean of a column

**OPERATIONS FOR DATAFRAME MISSING VALUES**




df2 = data_frame.copy()

df2.loc['C','Monday'] = np.nan

# what happens here is that we craete a nan value using np.nan

#mean = df2['Monday'].mean()

#df2['Monday'] = df2['Monday'].fillna(mean)

# here we filled all the nan values in monday column using .fillna(mean) - mean is what we calculated

#we can also drop missing data using dropna

df3 = df2.copy()

df3.dropna(how ='any', inplace=True)

#how='any': This parameter specifies that a row or column should be dropped if it contains any NaN values.
	#inplace=True: This parameter modifies the DataFrame in place, meaning the changes are applied to the existing DataFrame rather than returning a new one.


**File operations**

In [120]:
data_frame.to_csv('my_data.csv')# To save a file

df4 = pd.read_csv('my_data.csv')# to read a file

**Visualization**

%matplotlib inline
#to print on this page

ts = pd.Series(np.random.randn(5)) # creatiing a series

ts.plot() # to plot a series 

df4.plot()# plot a data frame
data_frame.plot(kind='bar')


**MatLab Operations**